# Generated by Django 5.1.7 on 2025-03-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
